//
//  main.swift
//  AdvenOfCode2015
//
//  Created by Justin Roughley on 29/12/2021.
//

import Foundation

//print("========== day 1")
//day1()
//print("========== day 2")
//day2()
//print("========== day 3")
//day3()
//print("========== day 4")
//day4()
//print("========== day 5")
//day5()
//print("========== day 6")
//day6()
//print("========== day 7")
//day7()
//print("========== day 8")
//day8()
//print("========== day 9")
//day9()
//print("========== day 10")
//day10()
//print("========== day 11")
//day11()
//print("========== day 12")
//day12()
//print("========== day 13")
//day13()
//print("========== day 14")
//day14()
//print("========== day 15")
//day15()
//print("========== day 16")
//day16()
//print("========== day 17")
//day17()
//print("========== day 18")
//day18()
//print("========== day 19")
//day19()
//print("========== day 20")
//day20()
//print("========== day 21")
//day21()
//print("========== day 22")
//day22()
//print("========== day 23")
//day23()
print("========== day 24")
day24()
//print("========== day 25")
//day25()
